version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm set progress=false
      - npm install -g @angular/cli@9.0.0
  pre_build:
    commands:
      - cp src/app/services/envs/env-${MATURITY}.ts src/app/services/env.ts
      - npm install --prod
  build:
    commands:
      - ng build --prod
  post_build:
    commands:
      - pwd
      - cd dist/${APPLICATION}
      - aws s3 sync . "s3://${S3_BUCKET}"
      - cd ../..
      - pwd
      - ls -la
      - chmod +x ./invalidate-cf.sh
      - . ./invalidate-cf.sh ${CDN_ID}
