version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g @angular/cli@6.2.4
  pre_build:
    commands:
      - cp src/assets/envs/env-${MATURITY}.js src/assets/env.js
      - npm install
  build:
    commands:
      - ng build --prod
  post_build:
    commands:
      - cd dist/${APPLICATION}
      - aws s3 sync . "s3://${S3_BUCKET}"
