contact_links:
  - name: Ask Questions
    url: https://github.com/asfadmin/Discovery-SearchUI/discussions
    about: Feel free to ask and answer questions in GitHub's Discussions

  - name: Gitter Chat
    url: https://gitter.im/ASFDiscovery/Vertex
    about: Come chat with the Vertex community
